# This is a basic workflow to help you get started with Actions

name: wf-1

# Controls when the workflow will run - the trigger
on:
  # manually trigger the workflow
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  first-job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps: 
      - name: echo foo
        run: echo "foo"
      - name: echo bar
        run: echo "bar"
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: echo baz - multilne script
        run: |
          echo "First output"
          echo "Second output"





    # Steps represent a sequence of tasks that will be
  # This workflow contains a single job called "build"















  # build:
  #   # The type of runner that the job will run on
  #   runs-on: ubuntu-latest

  #   # Steps represent a sequence of tasks that will be executed as part of the job
  #   steps:
  #     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  #     - uses: actions/checkout@v4

  #     # Runs a single command using the runners shell
  #     - name: Run a one-line script
  #       run: echo Hello, world!

  #     # Runs a set of commands using the runners shell
  #     - name: Run a multi-line script
  #       run: |
  #         echo Add other actions to build,
  #         echo test, and deploy your project.
