# This is a basic workflow to help you get started with Actions

name: wf-1

# Controls when the workflow will run - the trigger
on:
  # manually trigger the workflow
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  first-job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps: 
      - name: echo foo
        run: echo "on-push-foo"
      - name: echo bar
        run: echo "bar"
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: echo baz - multilne script
        run: |
          echo "First output"
          echo "Second output"